server:
  port: 8090
  servlet:
    context-path: /jeesite/

spring:
  application:
    name: jeesite
  mvc:
    static-path-pattern: /**
    http.multipart:
      max-request-size: 30MB
      max-file-size: 30MB
      resources:
        static-locations: classpath:/static/, classpath:/META-INF/resources/
  datasource:
    url: jdbc:mysql://localhost:3306/test_jeesite
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    init-db: true

    druid.initialSize: 3
    druid.maxActive: 15
    druid.minIdle: 2
    druid.maxWait: 60000
    druid.timeBetweenEvictionRunsMillis: 60000
    druid.minEvictableIdleTimeMillis: 300000
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456
#    timeout: 10000

# mybatis配置
mybatis:
  type-aliases-package: com.baojie.jeesite.*.entity
  mapper-locations: classpath:mapper/*.xml

# mybatis 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  file: logs/jeesite-web.log
  level:
    org.springframework: error
    com.baojie.jeesite: debug
    org.apache.shiro: debug
    org.quartz: error

jeesite:
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  websocket: false #是否开启websocket
  quartz: false #是否开启定时任务
  swagger: true #是否启用swagger







